fix: remove dependency on optional rspec-its gem
rspec-its isn't part of rspec, so it's not always going to be the case
that projects adopting the `ruby_rspec` rule will have a dependency on
this in their Gemfile.

```
ERROR: ~/projects/bazel/rules_ruby/examples/simple_script_vendored/BUILD.bazel:50:11: no such target '@bundle//:rspec-its': target 'rspec-its' not declared in package '' (did you mean 'rspec'?) defined by ~/.cache/bazel/_bazel_russell/0defde5a42a51f72cd789bdfc6b42615/external/bundle/BUILD.bazel and referenced by '//:ruby-rspec-test'
```